version: '3'

services:
  springboot-app:
    build: ./backend
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge