version: '3'

services:
  springboot-app:
    image: dhyeon/dhyeon-server:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network
    restart: always

  frontend:
    image: dhyeon/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge