version: '3'

services:
  springboot-app:
    image: dhyeon/dhyeon-server:latest
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge