version: '3.8'

services:
  backend:
    image: dhye5n/backend-app:latest
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    networks:
      - app-network

  frontend:
    image: dhye5n/frontend-app:latest
    container_name: frontend-container
    ports:
      - "80:80"
#    env_file:
#      - ./frontend/.env.prod
    environment:
      - NODE_ENV=prod
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge