version: '3'

services:
  backend:
    image: dhye5n/backend-app:latest  # 이미 푸시된 이미지 사용
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  frontend:
    image: dhye5n/frontend-app:latest  # 이미 푸시된 이미지 사용
    ports:
      - "80:80"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge