server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin_project?serverTimezone=UTC
    username: ENC(coV2QzHh9lTDI8zyZna73g==)
    password: ENC(wI0MWPVBlr3r2aEpd+VPTw==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(7+gD/4Hyy49nJYLIj2sfkLo8ifdK3Tkc9eFNBX+pw7g=)
    password: ENC(h1lBHjiuiA+Yh+uNiDRp/2VLOYDjRdOV)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

file:
  path: C:/fileUpload
  url: http://localhost:8080/api/v1/files/


jwt:
  secret-key: ${JWT_SECRET_KEY}