server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://dhyeon-mysql.cx606moisgcl.ap-northeast-2.rds.amazonaws.com:3306/admin_project?serverTimezone=UTC
    username: ENC(${DB_USERNAME})
    password: ENC(${DB_PASSWORD})
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(${MAIL_USERNAME})
    password: ENC(${MAIL_PASSWORD})
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

file:
  path: C:/fileUpload
  url: http://localhost:8080/api/v1/files/

jwt:
  secret-key: ${JWT_SECRET_KEY}