spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/admin_project?serverTimezone=UTC
    username: ENC(hjMovEvXslkNcBl8O/DATA==)
    password: ENC(15rwtWiFfquvgJpwQsZEZw==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.naver.com
    port: 587
    username: ENC(DEcVaQgStkpM3sL2VvQ3jS5lMOOzBcR4jSdQS3LDoyY=)
    password: ENC(n5E7A+TAUGIim46RzqpX3ARJdfgcHkft)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static:
        ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}

file:
  path: C:/fileUpload
  url: http://localhost:8080/api/v1/files/


jwt:
  secret-key: ${JWT_SECRET_KEY}

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

