server:
  port: 9994
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://dhyeon-mysql.clyeu8ok4dn0.ap-southeast-2.rds.amazonaws.com:3306/admin-project?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  mail:
    host: smtp.naver.com
    port: 587
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

jwt:
  secret-key: X2NyYXNoX3NlcnZpY2Vfc3VwZXJfc2VjcmV0X2tldF8=

file:
  path: C:/fileUpload/
  url: http://localhost:9994/files/