name: Build and Deploy

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Backend (Spring Boot)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd backend
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 사용자명
          password: ${{ secrets.DOCKER_TOKEN }}  # Docker Hub Access Token

      - name: Build Docker
        run: docker build --platform linux/amd64 -f backend/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/dhyeon-server .
      - name: Push Docker
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dhyeon-server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Server and Pull Docker Image
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_IP }}  # 배포할 서버의 IP
          key: ${{ secrets.EC2_SSH_KEY }}  # 서버 SSH 키
          script: |
            # Docker image pull and restart
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/dhyeon-server:latest
            sudo docker stop dhyeon-server || true  # Stops the container if it's running
            sudo docker rm dhyeon-server || true    # Removes the container if it's stopped
            sudo docker run -d --name dhyeon-server -p 8080:8080 \
            -e DB_USERNAME=${DB_USERNAME} \
            -e DB_PASSWORD=${DB_PASSWORD} \
            -e MAIL_USERNAME=${MAIL_USERNAME} \
            -e MAIL_PASSWORD=${MAIL_PASSWORD} \
            -e JWT_SECRET_KEY=${JWT_SECRET_KEY} \
            ${{ secrets.DOCKER_USERNAME }}/dhyeon-server:latest
