name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Backend and Frontend (Spring Boot + Nginx)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          cd backend
          chmod +x ./gradlew
          ./gradlew clean build -x test -Pprod
          ls -l build/libs

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 사용자명
          password: ${{ secrets.DOCKER_TOKEN }}  # Docker Hub Access Token

      - name: Build Docker (Backend)
        run: docker build --platform linux/amd64 -f backend/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/dhyeon-server backend/

      - name: Push Docker (Backend)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dhyeon-server:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: docker-compose.yml
          target: /home/ubuntu/admin-project/docker-compose.yml


      - name: SSH into Server and Pull Docker Image
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_IP }}  # 배포할 서버의 IP
          key: ${{ secrets.EC2_SSH_KEY }}  # 서버 SSH 키
          script: |
            # Docker image pull and restart
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/dhyeon-server:latest
            cd /home/ubuntu/admin-project 
            sudo docker-compose-plugin down || true
            sudo docker-compose-plugin up -d --force-recreate
            
        
